/*
 * Generated by dtrace(1M).
 */

#ifndef	_APP_STORE_H
#define	_APP_STORE_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define SYNCENGINE_SYNC_STABILITY "___dtrace_stability$syncengine_sync$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define SYNCENGINE_SYNC_TYPEDEFS "___dtrace_typedefs$syncengine_sync$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	SYNCENGINE_SYNC_STRATEGY_GO_TO_STATE(arg0) \
do { \
	__asm__ volatile(".reference " SYNCENGINE_SYNC_TYPEDEFS); \
	__dtrace_probe$syncengine_sync$strategy_go_to_state$v1$696e74(arg0); \
	__asm__ volatile(".reference " SYNCENGINE_SYNC_STABILITY); \
} while (0)
#define	SYNCENGINE_SYNC_STRATEGY_GO_TO_STATE_ENABLED() \
	({ int _r = __dtrace_isenabled$syncengine_sync$strategy_go_to_state$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$syncengine_sync$strategy_go_to_state$v1$696e74(int);
extern int __dtrace_isenabled$syncengine_sync$strategy_go_to_state$v1(void);

#else

#define	SYNCENGINE_SYNC_STRATEGY_GO_TO_STATE(arg0) \
do { \
	} while (0)
#define	SYNCENGINE_SYNC_STRATEGY_GO_TO_STATE_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _APP_STORE_H */
